#include "TelemetryHealthMetrics.h"
#include "Engine/World.h"
#include "Materials/MaterialInstanceDynamic.h"
ATJTelemetryCitadel::ATJTelemetryCitadel(){PrimaryActorTick.bCanEverTick=true;Root=CreateDefaultSubobject<USceneComponent>(TEXT("Root"));SetRootComponent(Root);PowerPlant=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PowerPlantCPU"));PowerPlant->SetupAttachment(Root);PressureVessels=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PressureVesselsRAM"));PressureVessels->SetupAttachment(Root);StorageSilos=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("StorageSilosDisk"));StorageSilos->SetupAttachment(Root);NetworkExchange=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("NetworkExchange"));NetworkExchange->SetupAttachment(Root);UptimeMonument=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("UptimeMonument"));UptimeMonument->SetupAttachment(Root);}
void ATJTelemetryCitadel::SetScalar(UPrimitiveComponent*C,FName P,float V)const{if(!C)return;for(int32 i=0;i<C->GetNumMaterials();++i)if(auto*M=C->CreateAndSetMaterialInstanceDynamic(i))M->SetScalarParameterValue(P,V);}
float ATJTelemetryCitadel::Strain(float V)const{return FMath::Clamp((V-0.55f)/0.45f,0.f,1.f);}
void ATJTelemetryCitadel::ApplyFacilityState(){const float C=FMath::Clamp(SystemMetrics.CPULoad01,0.f,1.f),M=FMath::Clamp(SystemMetrics.MemoryUsage01,0.f,1.f),D=FMath::Clamp(SystemMetrics.DiskUsage01,0.f,1.f),N=FMath::Clamp(SystemMetrics.NetworkThroughput01,0.f,1.f);SetScalar(PowerPlant,TEXT("MetricValue01"),C);SetScalar(PowerPlant,TEXT("DegradedStrained"),Strain(C));SetScalar(PressureVessels,TEXT("MetricValue01"),M);SetScalar(PressureVessels,TEXT("DegradedStrained"),Strain(M));SetScalar(StorageSilos,TEXT("MetricValue01"),D);SetScalar(StorageSilos,TEXT("DegradedStrained"),Strain(D));SetScalar(NetworkExchange,TEXT("MetricValue01"),N);SetScalar(NetworkExchange,TEXT("DegradedStrained"),Strain(N));SetScalar(UptimeMonument,TEXT("UptimeSeconds"),FMath::Clamp((float)SystemMetrics.UptimeSeconds,0.f,1000000.f));}
void ATJTelemetryCitadel::SetSystemMetrics(const FTJSystemMetrics&M){SystemMetrics=M;ApplyFacilityState();}
void ATJTelemetryCitadel::SetContainerMetrics(const FTJContainerMetrics&M){if(M.ContainerId.IsEmpty())return;Containers.Add(M.ContainerId,M);}
bool ATJTelemetryCitadel::RenderSystemMetrics(){ApplyFacilityState();return true;} bool ATJTelemetryCitadel::RenderCPU(){ApplyFacilityState();return true;} bool ATJTelemetryCitadel::RenderMemory(){ApplyFacilityState();return true;} bool ATJTelemetryCitadel::RenderDisk(){ApplyFacilityState();return true;} bool ATJTelemetryCitadel::RenderNetwork(){ApplyFacilityState();return true;} bool ATJTelemetryCitadel::RenderUptime(){ApplyFacilityState();return true;}
bool ATJTelemetryCitadel::TriggerAlert(ETJAlertSeverity S,const FString&Source){if(Source.IsEmpty())return false;Alerts.Add({S,Source,RuntimeSeconds});auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);AlertEvents.Add(C);SetScalar(C,TEXT("SystemAlert01"),(float)((uint8)S+1)/3.f);return true;}
bool ATJTelemetryCitadel::RenderContainer(const FString&Id){if(!Containers.Contains(Id))return false;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);ContainerFacilities.Add(C);const auto&M=Containers[Id].Metrics;const float Peak=FMath::Max(FMath::Max(M.CPULoad01,M.MemoryUsage01),FMath::Max(M.DiskUsage01,M.NetworkThroughput01));SetScalar(C,TEXT("ContainerMetricValue01"),Peak);SetScalar(C,TEXT("DegradedStrained"),Strain(Peak));return true;}
void ATJTelemetryCitadel::Tick(float Dt){Super::Tick(Dt);RuntimeSeconds+=Dt;SystemMetrics.UptimeSeconds=RuntimeSeconds;ApplyFacilityState();}
ATJTelemetryCitadel* UTJTelemetryHealthMetrics::BuildTelemetryCitadel(){if(!Citadel){if(!GetWorld())return nullptr;Citadel=GetWorld()->SpawnActor<ATJTelemetryCitadel>();}return Citadel;}
bool UTJTelemetryHealthMetrics::RenderSystemMetrics(){return Citadel&&Citadel->RenderSystemMetrics();} bool UTJTelemetryHealthMetrics::RenderCPULoad(){return Citadel&&Citadel->RenderCPU();} bool UTJTelemetryHealthMetrics::RenderMemoryUsage(){return Citadel&&Citadel->RenderMemory();} bool UTJTelemetryHealthMetrics::RenderDiskUsage(){return Citadel&&Citadel->RenderDisk();} bool UTJTelemetryHealthMetrics::RenderNetworkThroughput(){return Citadel&&Citadel->RenderNetwork();} bool UTJTelemetryHealthMetrics::RenderUptime(){return Citadel&&Citadel->RenderUptime();} bool UTJTelemetryHealthMetrics::TriggerSystemAlert(ETJAlertSeverity S,const FString&Source){return Citadel&&Citadel->TriggerAlert(S,Source);} bool UTJTelemetryHealthMetrics::RenderContainerMetrics(const FString&Id){return Citadel&&Citadel->RenderContainer(Id);} void UTJTelemetryHealthMetrics::SetSystemMetrics(const FTJSystemMetrics&M){if(Citadel)Citadel->SetSystemMetrics(M);} void UTJTelemetryHealthMetrics::SetContainerMetrics(const FTJContainerMetrics&M){if(Citadel)Citadel->SetContainerMetrics(M);}