#include "ErrorDegradationHandling.h"
bool UTJErrorDegradationHandling::RegisterSystem(const FString&S){if(S.IsEmpty())return false;FTJSystemHealth&H=Health.FindOrAdd(S);H.System=S;H.State=ETJHealthState::Healthy;H.Reason.Empty();return true;}
void UTJErrorDegradationHandling::SetHealth(const FString&S,ETJHealthState St,const FString&R){if(S.IsEmpty())return;FTJSystemHealth&H=Health.FindOrAdd(S);H.System=S;H.State=St;H.Reason=R;}
void UTJErrorDegradationHandling::AddError(const FString&Id,const FString&M,ETJErrorSeverity Sev,const FString&Scope){FTJErrorRecord E;E.ErrorId=Id;E.Message=M;E.Severity=Sev;E.Scope=Scope;E.bActionable=true;Errors.Add(Id,E);}
bool UTJErrorDegradationHandling::SurfaceError(const FTJErrorRecord&E){if(E.ErrorId.IsEmpty()||E.Message.IsEmpty())return false;Errors.Add(E.ErrorId,E);SetHealth(E.Scope, E.Severity==ETJErrorSeverity::Critical?ETJHealthState::Failed:ETJHealthState::Degraded,E.Message);bDegraded=true;return true;}
bool UTJErrorDegradationHandling::HandleBackendLoss(const FString&R){if(R.IsEmpty())return false;bReadOnlyCached=true;bDegraded=true;SetHealth(TEXT("backend"),ETJHealthState::Degraded,R);AddError(TEXT("backend-loss"),FString::Printf(TEXT("Backend unavailable: %s. Running from cached state; writes are disabled."),*R),ETJErrorSeverity::Critical,TEXT("backend"));return true;}
bool UTJErrorDegradationHandling::HandleSyncBridgeLoss(){bSyncPending=true;bDegraded=true;SetHealth(TEXT("sync"),ETJHealthState::Degraded,TEXT("Sync bridge unavailable; local actions are queued."));AddError(TEXT("sync-loss"),TEXT("Sync bridge unavailable. Local actions are pending and have not been confirmed remotely."),ETJErrorSeverity::Warning,TEXT("sync"));return true;}
bool UTJErrorDegradationHandling::HandleWorldLoadFailure(const FString&Region,const FString&E){if(Region.IsEmpty()||E.IsEmpty())return false;bDegraded=true;SetHealth(FString::Printf(TEXT("world:%s"),*Region),ETJHealthState::Failed,E);AddError(FString::Printf(TEXT("world-load:%s"),*Region),FString::Printf(TEXT("World region %s failed to load: %s. Placeholder void is shown."),*Region,*E),ETJErrorSeverity::Critical,FString::Printf(TEXT("world:%s"),*Region));return true;}
bool UTJErrorDegradationHandling::HandleServiceCrash(const FString&P,const FString&C){if(P.IsEmpty()||C.IsEmpty())return false;bDegraded=true;SetHealth(FString::Printf(TEXT("service:%s"),*P),ETJHealthState::Failed,TEXT("Service container crashed."));AddError(FString::Printf(TEXT("service-crash:%s"),*P),FString::Printf(TEXT("Service %s crashed in container %s. Service state must be Error; restart/recovery is required."),*P,*C),ETJErrorSeverity::Critical,FString::Printf(TEXT("service:%s"),*P));return true;}
bool UTJErrorDegradationHandling::EnterDegradedMode(ETJDegradedScope Scope,const FString&R){if(R.IsEmpty())return false;bDegraded=true;SetHealth(UEnum::GetValueAsString(Scope),ETJHealthState::Degraded,R);AddError(FString::Printf(TEXT("degraded:%d"),(int32)Scope),FString::Printf(TEXT("Degraded mode active: %s"),*R),ETJErrorSeverity::Warning,UEnum::GetValueAsString(Scope));return true;}
bool UTJErrorDegradationHandling::ExitDegradedMode(){if(bReadOnlyCached||bSyncPending)return false;bDegraded=false;for(auto&K:Health)if(K.Value.State==ETJHealthState::Degraded)K.Value.State=ETJHealthState::Healthy;return true;}
bool UTJErrorDegradationHandling::RecoverWorldState(){if(bReadOnlyCached||bSyncPending){AddError(TEXT("recovery-blocked"),TEXT("World recovery cannot be confirmed while backend or sync is unavailable."),ETJErrorSeverity::Warning,TEXT("world"));return false;}bDegraded=false;SetHealth(TEXT("world"),ETJHealthState::Healthy,TEXT("World recovery requested from authoritative state-sync."));return true;}
bool UTJErrorDegradationHandling::ResolveError(const FString&Id){if(!Errors.Contains(Id))return false;Errors[Id].bActive=false;Errors.Remove(Id);return true;}
FTJAggregateHealth UTJErrorDegradationHandling::GetSystemHealth()const{FTJAggregateHealth R;R.State=ETJHealthState::Healthy;for(const auto&K:Health)R.Systems.Add(K.Value);for(const auto&K:Errors)if(K.Value.bActive)R.ActiveErrors.Add(K.Value);for(const auto&S:R.Systems){if(S.State==ETJHealthState::Failed){R.State=ETJHealthState::Failed;break;}if(S.State==ETJHealthState::Degraded)R.State=ETJHealthState::Degraded;}if(R.Systems.Num()==0)R.State=ETJHealthState::Unknown;return R;}