#include "BackupVault.h"
#include "Engine/World.h"
#include "Materials/MaterialInstanceDynamic.h"
ATJBackupVault::ATJBackupVault(){PrimaryActorTick.bCanEverTick=true;Root=CreateDefaultSubobject<USceneComponent>(TEXT("Root"));SetRootComponent(Root);VaultWing=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("VaultWing"));VaultWing->SetupAttachment(Root);CalendarObelisk=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("CalendarObelisk"));CalendarObelisk->SetupAttachment(Root);}
void ATJBackupVault::SetScalar(UPrimitiveComponent*C,FName P,float V)const{if(!C)return;for(int32 i=0;i<C->GetNumMaterials();++i)if(auto*M=C->CreateAndSetMaterialInstanceDynamic(i))M->SetScalarParameterValue(P,V);}
bool ATJBackupVault::Build(){if(!VaultWing)return false;SetScalar(VaultWing,TEXT("VaultWing01"),1);return true;}
void ATJBackupVault::RegisterTarget(const FTJBackupTarget&T){if(!T.TargetId.IsEmpty())Targets.Add(T.TargetId,T);}
void ATJBackupVault::RegisterSchedule(const FTJBackupSchedule&S){if(!S.ScheduleId.IsEmpty())Schedules.Add(S.ScheduleId,S);}
bool ATJBackupVault::RenderTarget(const FString&Id){if(!Targets.Contains(Id))return false;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);Chambers.Add(C);SetScalar(C,TEXT("BackupChamber01"),1);return true;}
void ATJBackupVault::RenderDissolution(const FString&TargetId){auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);DissolutionEffects.Add(C);SetScalar(C,TEXT("DifferentialDissolve01"),1);}
bool ATJBackupVault::Create(const FString&Pkg,const FString&Tid){if(Pkg.IsEmpty()||!Targets.Contains(Tid))return false;for(auto&K:Backups)if(K.Value.TargetId==Tid&&K.Value.State!=ETJBackupState::Deleted){K.Value.State=ETJBackupState::Superseded;RenderDissolution(Tid);}FString Id=Pkg+TEXT("@")+FGuid::NewGuid().ToString(EGuidFormats::Digits);Backups.Add(Id,{Id,Pkg,Tid,TEXT("current"),ETJBackupState::Creating,0,TEXT("")});auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);Monoliths.Add(C);SetScalar(C,TEXT("BackupMonolith01"),1);return true;}
bool ATJBackupVault::Progress(const FString&Pkg,float V){bool Found=false;for(auto&K:Backups)if(K.Value.PackageId==Pkg&&K.Value.State==ETJBackupState::Creating){K.Value.Progress01=FMath::Clamp(V,0.f,1.f);Found=true;SetScalar(VaultWing,TEXT("BackupProgress01"),K.Value.Progress01);if(K.Value.Progress01>=1)K.Value.State=ETJBackupState::Current;}return Found;}
bool ATJBackupVault::Verify(const FString&Id){auto*B=Backups.Find(Id);if(!B||B->State==ETJBackupState::Deleted)return false;B->IntegrityDigest=FString::Printf(TEXT("sha256:%s"),*FGuid::NewGuid().ToString(EGuidFormats::Digits));B->State=ETJBackupState::Verified;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);IntegritySeals.Add(C);SetScalar(C,TEXT("IntegrityVerified01"),1);return true;}
bool ATJBackupVault::Restore(const FString&Id,const FString&Svc){auto*B=Backups.Find(Id);if(!B||Svc.IsEmpty()||B->State==ETJBackupState::Deleted)return false;auto*I=InterlocksState.Find(Id);if(!I||!I->bEngaged)return false;B->State=ETJBackupState::Restoring;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);RestoreDischarges.Add(C);SetScalar(C,TEXT("RestoreDischarge01"),1);return true;}
bool ATJBackupVault::HoldRestoreInterlock(const FString&Id,float Dt){if(!Backups.Contains(Id)||Dt<=0)return false;auto&I=InterlocksState.FindOrAdd(Id);I.MonolithId=Id;I.HoldSeconds+=Dt;if(I.HoldSeconds>=2)I.bEngaged=true;return true;}
bool ATJBackupVault::ReleaseRestoreInterlock(const FString&Id){auto*I=InterlocksState.Find(Id);if(!I)return false;if(I->HoldSeconds<2)return false;I->HoldSeconds=0;I->bEngaged=false;return true;}
bool ATJBackupVault::Delete(const FString&Id){auto*B=Backups.Find(Id);if(!B||B->State==ETJBackupState::Deleted)return false;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);DeleteWarnings.Add(C);SetScalar(C,TEXT("OnlyRestorePointWarning01"),1);B->State=ETJBackupState::Deleted;return true;}
bool ATJBackupVault::RenderSchedule(){SetScalar(CalendarObelisk,TEXT("BackupSchedule01"),Schedules.Num()>0?1.f:0.f);return true;}
void ATJBackupVault::Tick(float Dt){Super::Tick(Dt);}
ATJBackupVault* UTJBackupVault::BuildBackupVault(){if(!Vault){if(!GetWorld())return nullptr;Vault=GetWorld()->SpawnActor<ATJBackupVault>();}return Vault->Build()?Vault:nullptr;}
bool UTJBackupVault::RenderBackupTarget(const FString&Id){return Vault&&Vault->RenderTarget(Id);} bool UTJBackupVault::CreateBackup(const FString&P,const FString&T){return Vault&&Vault->Create(P,T);} bool UTJBackupVault::RenderBackupProgress(const FString&P,float V){return Vault&&Vault->Progress(P,V);} bool UTJBackupVault::RestoreBackup(const FString&I,const FString&T){return Vault&&Vault->Restore(I,T);} bool UTJBackupVault::VerifyBackupIntegrity(const FString&I){return Vault&&Vault->Verify(I);} bool UTJBackupVault::DeleteBackup(const FString&I){return Vault&&Vault->Delete(I);} bool UTJBackupVault::RenderBackupSchedule(){return Vault&&Vault->RenderSchedule();} bool UTJBackupVault::HoldRestoreInterlock(const FString&I,float D){return Vault&&Vault->HoldRestoreInterlock(I,D);} bool UTJBackupVault::ReleaseRestoreInterlock(const FString&I){return Vault&&Vault->ReleaseRestoreInterlock(I);} void UTJBackupVault::RegisterTarget(const FTJBackupTarget&T){if(Vault)Vault->RegisterTarget(T);} void UTJBackupVault::RegisterSchedule(const FTJBackupSchedule&S){if(Vault)Vault->RegisterSchedule(S);}