#include "ServiceLifecycle.h"
#include "Engine/World.h"
#include "Materials/MaterialInstanceDynamic.h"
ATJServiceLifecycleSpace::ATJServiceLifecycleSpace(){PrimaryActorTick.bCanEverTick=true;Root=CreateDefaultSubobject<USceneComponent>(TEXT("Root"));SetRootComponent(Root);BuildingConsole=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ControlRoom"));BuildingConsole->SetupAttachment(Root);Ignition=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("PhysicalIgnition"));Ignition->SetupAttachment(Root);ShutdownConsole=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ShutdownConsole"));ShutdownConsole->SetupAttachment(Root);ForcedStopLever=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ForcedStopLever"));ForcedStopLever->SetupAttachment(Root);DoorBarrier=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("CriticalTaskDoorBarrier"));DoorBarrier->SetupAttachment(Root);}
void ATJServiceLifecycleSpace::SetScalar(UPrimitiveComponent*C,FName P,float V)const{if(!C)return;for(int32 i=0;i<C->GetNumMaterials();++i)if(auto*M=C->CreateAndSetMaterialInstanceDynamic(i))M->SetScalarParameterValue(P,V);}
void ATJServiceLifecycleSpace::RegisterService(const FTJServiceRuntime&R,const TArray<FTJSDKAction>&A,const TArray<FTJServiceTask>&T,const TArray<FTJHealthCheck>&H,const TArray<FTJServiceLogEntry>&L,const FTJServiceConfig&C){if(R.PackageId.IsEmpty())return;Services.Add(R.PackageId,R);Actions.Add(R.PackageId,A);Tasks.Add(R.PackageId,T);Health.Add(R.PackageId,H);Logs.Add(R.PackageId,L);Configs.Add(R.PackageId,C);RefreshDoor(R.PackageId);}
bool ATJServiceLifecycleSpace::Start(const FString&Id){auto*S=Services.Find(Id);if(!S)return false;if(S->State!=ETJServiceLifecycleState::Stopped)return false;S->State=ETJServiceLifecycleState::Starting;SetScalar(Ignition,TEXT("Ignition01"),1);S->State=ETJServiceLifecycleState::Running;return true;}
bool ATJServiceLifecycleSpace::Stop(const FString&Id,bool G){auto*S=Services.Find(Id);if(!S)return false;if(G){if(S->State==ETJServiceLifecycleState::Stopped)return true;S->State=ETJServiceLifecycleState::Stopping;SetScalar(ShutdownConsole,TEXT("GracefulShutdown01"),1);S->State=ETJServiceLifecycleState::Stopped;return true;}S->ForcedStopHoldSeconds=0;SetScalar(ForcedStopLever,TEXT("ForcedStopArmed01"),1);return true;}
bool ATJServiceLifecycleSpace::HoldForcedStopLever(const FString&Id,float Dt){auto*S=Services.Find(Id);if(!S||Dt<=0)return false;S->ForcedStopHoldSeconds+=Dt;if(S->ForcedStopHoldSeconds>=3){S->State=ETJServiceLifecycleState::Stopped;SetScalar(ForcedStopLever,TEXT("ForcedStopComplete01"),1);return true;}return true;}
bool ATJServiceLifecycleSpace::ReleaseForcedStopLever(const FString&Id){auto*S=Services.Find(Id);if(!S)return false;if(S->ForcedStopHoldSeconds<3)return false;S->ForcedStopHoldSeconds=0;return true;}
bool ATJServiceLifecycleSpace::RenderActions(const FString&Id){return Services.Contains(Id)&&Actions.Contains(Id);}
bool ATJServiceLifecycleSpace::Execute(const FString&Id,const FString&A,const FString&Input){if(!Services.Contains(Id)||A.IsEmpty())return false;for(const auto&X:Actions[Id])if(X.ActionId==A){auto*Log=Logs.Find(Id);if(Log)Log->Add({FDateTime::UtcNow().ToIso8601(),TEXT("ACTION"),A+TEXT(" executed: ")+Input});SetScalar(BuildingConsole,TEXT("ActionFeedback01"),1);return true;}return false;}
bool ATJServiceLifecycleSpace::RenderTasks(const FString&Id){if(!Services.Contains(Id))return false;RefreshDoor(Id);return Tasks.Contains(Id);}
void ATJServiceLifecycleSpace::RefreshDoor(const FString&Id){bool B=false;if(auto*T=Tasks.Find(Id))for(const auto&X:*T)if(X.Severity==ETJTaskSeverity::Critical&&!X.bResolved){B=true;break;}if(auto*S=Services.Find(Id))S->bCriticalDoorBlocked=B;SetScalar(DoorBarrier,TEXT("CriticalDoorBarrier01"),B?1.f:0.f);}
bool ATJServiceLifecycleSpace::ResolveTask(const FString&Id,const FString&Tid){auto*T=Tasks.Find(Id);if(!T)return false;for(auto&X:*T)if(X.TaskId==Tid){X.bResolved=true;RefreshDoor(Id);return true;}return false;}
bool ATJServiceLifecycleSpace::RenderHealth(const FString&Id){return Services.Contains(Id)&&Health.Contains(Id);}
bool ATJServiceLifecycleSpace::RenderLogs(const FString&Id){return Services.Contains(Id)&&Logs.Contains(Id);}
bool ATJServiceLifecycleSpace::RenderConfig(const FString&Id){return Services.Contains(Id)&&Configs.Contains(Id);}
void ATJServiceLifecycleSpace::Tick(float Dt){Super::Tick(Dt);}
ATJServiceLifecycleSpace* UTJServiceLifecycle::BuildSpace(){if(!Space){if(!GetWorld())return nullptr;Space=GetWorld()->SpawnActor<ATJServiceLifecycleSpace>();}return Space;}
bool UTJServiceLifecycle::StartService(const FString&Id){return Space&&Space->Start(Id);} bool UTJServiceLifecycle::StopService(const FString&Id,bool G){return Space&&Space->Stop(Id,G);}
bool UTJServiceLifecycle::RenderSDKActions(const FString&Id){return Space&&Space->RenderActions(Id);} bool UTJServiceLifecycle::ExecuteAction(const FString&Id,const FString&A,const FString&I){return Space&&Space->Execute(Id,A,I);}
bool UTJServiceLifecycle::RenderTasks(const FString&Id){return Space&&Space->RenderTasks(Id);} bool UTJServiceLifecycle::RenderHealthChecks(const FString&Id){return Space&&Space->RenderHealth(Id);} bool UTJServiceLifecycle::RenderServiceLogs(const FString&Id){return Space&&Space->RenderLogs(Id);} bool UTJServiceLifecycle::RenderConfiguration(const FString&Id){return Space&&Space->RenderConfig(Id);}
bool UTJServiceLifecycle::HoldForcedStopLever(const FString&Id,float Dt){return Space&&Space->HoldForcedStopLever(Id,Dt);} bool UTJServiceLifecycle::ReleaseForcedStopLever(const FString&Id){return Space&&Space->ReleaseForcedStopLever(Id);} bool UTJServiceLifecycle::ResolveTask(const FString&Id,const FString&T){return Space&&Space->ResolveTask(Id,T);}
void UTJServiceLifecycle::RegisterService(const FTJServiceRuntime&R,const TArray<FTJSDKAction>&A,const TArray<FTJServiceTask>&T,const TArray<FTJHealthCheck>&H,const TArray<FTJServiceLogEntry>&L,const FTJServiceConfig&C){if(Space)Space->RegisterService(R,A,T,H,L,C);}
