#pragma once
#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "NavigationSystem.h"
#include "NavMesh/RecastNavMesh.h"
#include "NavLinkProxy.h"
#include "NavMeshPathfinding.generated.h"
UENUM(BlueprintType) enum class ETJNavAreaTag : uint8 { Sidewalk, Road, Crosswalk, Interior, Restricted };
USTRUCT(BlueprintType) struct TJSPACE_API FTJNavGenerationParams { GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) float AgentRadius=42.f; UPROPERTY(EditAnywhere,BlueprintReadWrite) float AgentHeight=180.f; UPROPERTY(EditAnywhere,BlueprintReadWrite) float StepHeight=45.f; UPROPERTY(EditAnywhere,BlueprintReadWrite) float MaxSlope=44.f; UPROPERTY(EditAnywhere,BlueprintReadWrite) float TileSize=1024.f; UPROPERTY(EditAnywhere,BlueprintReadWrite) float CellSize=5.f; UPROPERTY(EditAnywhere,BlueprintReadWrite) float CellHeight=10.f; UPROPERTY(EditAnywhere,BlueprintReadWrite) bool bDynamic=true; bool IsValid() const { return AgentRadius>0&&AgentHeight>AgentRadius*2&&StepHeight>=0&&MaxSlope>0&&MaxSlope<89&&TileSize>=128&&CellSize>=1&&CellHeight>=1; } };
USTRUCT(BlueprintType) struct TJSPACE_API FTJNavRegion { GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) FBox Bounds=FBox(EForceInit::ForceInit); UPROPERTY(EditAnywhere,BlueprintReadWrite) FString RegionId; };
USTRUCT(BlueprintType) struct TJSPACE_API FTJPathOptions { GENERATED_BODY() UPROPERTY(EditAnywhere,BlueprintReadWrite) bool bHierarchical=true; UPROPERTY(EditAnywhere,BlueprintReadWrite) bool bSmooth=true; UPROPERTY(EditAnywhere,BlueprintReadWrite) bool bAllowPartial=false; UPROPERTY(EditAnywhere,BlueprintReadWrite) float SmoothingTolerance=18.f; };
USTRUCT(BlueprintType) struct TJSPACE_API FTJNavPathResult { GENERATED_BODY() UPROPERTY(BlueprintReadOnly) TArray<FVector> Polyline; UPROPERTY(BlueprintReadOnly) bool bSuccess=false; UPROPERTY(BlueprintReadOnly) bool bPartial=false; UPROPERTY(BlueprintReadOnly) float Length=0.f; UPROPERTY(BlueprintReadOnly) FString Failure; };
USTRUCT(BlueprintType) struct TJSPACE_API FTJNavIslandReport { GENERATED_BODY() UPROPERTY(BlueprintReadOnly) int32 PolygonCount=0; UPROPERTY(BlueprintReadOnly) int32 IslandCount=0; UPROPERTY(BlueprintReadOnly) TArray<int32> IslandSizes; UPROPERTY(BlueprintReadOnly) bool bConnected=false; };
UCLASS() class TJSPACE_API ATJNavTraversalLink : public ANavLinkProxy { GENERATED_BODY() public: ATJNavTraversalLink(); UPROPERTY(EditAnywhere,BlueprintReadWrite) FName TraversalTag; UPROPERTY(EditAnywhere,BlueprintReadWrite) float TraversalDuration=1.f; };
UCLASS(BlueprintType) class TJSPACE_API UTJNavMeshPathfinding : public UObject { GENERATED_BODY() public: UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") bool GenerateNavMesh(const FTJNavRegion& Region,const FTJNavGenerationParams& Params); UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") bool TagNavArea(const FTJNavRegion& Region,const TArray<ETJNavAreaTag>& Tags); UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") FTJNavPathResult QueryPath(const FVector& From,const FVector& To,const FTJPathOptions& Options) const; UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") bool AddDynamicObstacle(AActor* Actor,const FBox& Bounds); UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") bool RemoveDynamicObstacle(AActor* Actor); UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") FBox GetWalkableArea(const FBox& Bounds) const; UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") bool RebuildIncremental(const FTJNavRegion& ChangedRegion); UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") FTJNavIslandReport ValidateConnectivity() const; UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") bool RegisterTraversalLink(ATJNavTraversalLink* Link); UFUNCTION(BlueprintCallable,Category="TJ SPACE|Navigation") bool UnregisterTraversalLink(ATJNavTraversalLink* Link); UFUNCTION(BlueprintPure,Category="TJ SPACE|Navigation") float GetAgentRadius() const { return Generation.AgentRadius; } private: bool Project(const FVector& P,FNavLocation& Out) const; bool SmoothPath(TArray<FVector>& Points,float Tolerance) const; UPROPERTY() TObjectPtr<UWorld> World; UPROPERTY() TObjectPtr<ARecastNavMesh> NavMesh; TMap<TWeakObjectPtr<AActor>,FBox> Obstacles; TMap<FString,TArray<ETJNavAreaTag>> RegionTags; FTJNavGenerationParams Generation; };