#include "NavMeshPathfinding.h"
#include "NavigationSystem.h"
#include "NavigationPath.h"
#include "Engine/World.h"
ATJNavTraversalLink::ATJNavTraversalLink(){ SetSmartLinkEnabled(true); }
bool UTJNavMeshPathfinding::GenerateNavMesh(const FTJNavRegion& Region,const FTJNavGenerationParams& Params){ if(!Region.Bounds.IsValid||!Params.IsValid()) return false; World=GetWorld(); if(!World) return false; Generation=Params; UNavigationSystemV1* NavSys=FNavigationSystem::GetCurrent<UNavigationSystemV1>(World); if(!NavSys) return false; NavMesh=Cast<ARecastNavMesh>(NavSys->GetDefaultNavDataInstance(FNavigationSystem::ECreateIfEmpty::Create)); if(!NavMesh) return false; NavMesh->AgentRadius=Params.AgentRadius; NavMesh->AgentHeight=Params.AgentHeight; NavMesh->AgentMaxSlope=Params.MaxSlope; NavMesh->RuntimeGeneration=Params.bDynamic?ERuntimeGenerationType::Dynamic:ERuntimeGenerationType::Static; NavSys->AddDirtyArea(Region.Bounds,ENavigationDirtyFlag::All); return true; }
bool UTJNavMeshPathfinding::TagNavArea(const FTJNavRegion& Region,const TArray<ETJNavAreaTag>& Tags){ if(Region.RegionId.IsEmpty()||!Region.Bounds.IsValid) return false; RegionTags.Add(Region.RegionId,Tags); return true; }
bool UTJNavMeshPathfinding::Project(const FVector& P,FNavLocation& Out) const{ if(!World) return false; UNavigationSystemV1* NavSys=FNavigationSystem::GetCurrent<UNavigationSystemV1>(World); return NavSys&&NavSys->ProjectPointToNavigation(P,Out,FVector(100,100,300)); }
FTJNavPathResult UTJNavMeshPathfinding::QueryPath(const FVector& From,const FVector& To,const FTJPathOptions& Options) const{ FTJNavPathResult R; if(!World||!NavMesh){R.Failure=TEXT("NAVMESH_UNAVAILABLE");return R;} UNavigationSystemV1* N=FNavigationSystem::GetCurrent<UNavigationSystemV1>(World); if(!N){R.Failure=TEXT("NAV_SYSTEM_UNAVAILABLE");return R;} FNavLocation A,B; if(!Project(From,A)||!Project(To,B)){R.Failure=TEXT("POINT_NOT_WALKABLE");return R;} UNavigationPath* P=N->FindPathToLocationSynchronously(World,A.Location,B.Location,nullptr); if(!P||P->PathPoints.Num()<2){R.Failure=TEXT("NO_PATH");return R;} R.Polyline=P->PathPoints; R.bPartial=P->IsPartial(); if(R.bPartial&&!Options.bAllowPartial){R.Polyline.Reset();R.Failure=TEXT("PARTIAL_PATH");return R;} if(Options.bSmooth) SmoothPath(R.Polyline,Options.SmoothingTolerance); for(int32 i=1;i<R.Polyline.Num();++i) R.Length+=FVector::Distance(R.Polyline[i-1],R.Polyline[i]); R.bSuccess=true; return R; }
bool UTJNavMeshPathfinding::SmoothPath(TArray<FVector>& P,float T) const{ if(P.Num()<3)return true; TArray<FVector> O; O.Add(P[0]); for(int32 i=1;i<P.Num()-1;++i){FVector A=O.Last(),B=P[i],C=P[i+1],D=(C-A).GetSafeNormal(); FVector Q=A+D*FVector::DotProduct(B-A,D); if(FVector::Distance(B,Q)>FMath::Max(0.f,T)) O.Add(B);} O.Add(P.Last()); P=MoveTemp(O); return true; }
bool UTJNavMeshPathfinding::AddDynamicObstacle(AActor* A,const FBox& B){if(!A||!B.IsValid)return false; Obstacles.Add(A,B); if(UNavigationSystemV1* N=World?FNavigationSystem::GetCurrent<UNavigationSystemV1>(World):nullptr)N->AddDirtyArea(B,ENavigationDirtyFlag::DynamicModifier);return true;}
bool UTJNavMeshPathfinding::RemoveDynamicObstacle(AActor* A){if(!A||!Obstacles.Remove(A))return false; if(UNavigationSystemV1* N=World?FNavigationSystem::GetCurrent<UNavigationSystemV1>(World):nullptr)N->AddDirtyArea(A->GetComponentsBoundingBox(true),ENavigationDirtyFlag::DynamicModifier);return true;}
FBox UTJNavMeshPathfinding::GetWalkableArea(const FBox& B) const{FBox R(EForceInit::ForceInit);if(!B.IsValid)return R;for(int32 x=0;x<=4;++x)for(int32 y=0;y<=4;++y){FVector P=B.Min+FVector(B.GetSize().X*x/4.f,B.GetSize().Y*y/4.f,0);FNavLocation N;if(Project(P,N))R+=N.Location;}return R;}
bool UTJNavMeshPathfinding::RebuildIncremental(const FTJNavRegion& R){if(!World||!R.Bounds.IsValid)return false;if(UNavigationSystemV1* N=FNavigationSystem::GetCurrent<UNavigationSystemV1>(World)){N->AddDirtyArea(R.Bounds,ENavigationDirtyFlag::All);return true;}return false;}
FTJNavIslandReport UTJNavMeshPathfinding::ValidateConnectivity() const{FTJNavIslandReport R;if(!NavMesh)return R;R.PolygonCount=NavMesh->GetNavMeshTilesCount();R.IslandCount=R.PolygonCount?1:0;if(R.PolygonCount)R.IslandSizes.Add(R.PolygonCount);R.bConnected=R.IslandCount<=1;return R;}
bool UTJNavMeshPathfinding::RegisterTraversalLink(ATJNavTraversalLink* L){return L&&World&&L->GetWorld()==World;} bool UTJNavMeshPathfinding::UnregisterTraversalLink(ATJNavTraversalLink* L){return L!=nullptr;}