#include "LogsEventsObservability.h"
ATJArchiveObservability::ATJArchiveObservability(){PrimaryActorTick.bCanEverTick=true;Root=CreateDefaultSubobject<USceneComponent>(TEXT("Root"));SetRootComponent(Root);ArchiveTower=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ArchiveTower"));ArchiveTower->SetupAttachment(Root);EventRailway=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("EventBusRailway"));EventRailway->SetupAttachment(Root);Ledger=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("AuditLedger"));Ledger->SetupAttachment(Root);ExportCrystals=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("ExportCrystals"));ExportCrystals->SetupAttachment(Root);RetentionShelves=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("RetentionShelves"));RetentionShelves->SetupAttachment(Root);}
void ATJArchiveObservability::SetScalar(UPrimitiveComponent*C,FName P,float V)const{if(!C)return;for(int32 i=0;i<C->GetNumMaterials();++i)if(auto*M=C->CreateAndSetMaterialInstanceDynamic(i))M->SetScalarParameterValue(P,V);}
bool ATJArchiveObservability::BuildArchiveTower(){SetScalar(ArchiveTower,TEXT("ArchiveActive01"),1);ApplyAudioProfile();return true;}
bool ATJArchiveObservability::ValidTopic(const FString&T)const{return T.StartsWith(TEXT("tjs."))&&T.Contains(TEXT("."))&&T.Len()>4;}
void ATJArchiveObservability::AddLog(const FTJLogRecord&R){if(!ValidTopic(R.Topic))return;Logs.Add(R);SetScalar(ArchiveTower,TEXT("LogCount"),(float)Logs.Num());}
bool ATJArchiveObservability::StreamLogsToArchive(const FString&Source){if(Source.IsEmpty())return false;FTJLogRecord R;R.TimestampSeconds=RuntimeSeconds;R.Source=Source;R.Topic=FString::Printf(TEXT("tjs.%s.ingested"),*Source);R.Message=TEXT("live log stream");AddLog(R);auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);LogStreams.Add(C);SetScalar(C,TEXT("LogStream01"),1);return true;}
TArray<FTJLogRecord> ATJArchiveObservability::QueryArchive(const FTJArchiveFilter&F)const{TArray<FTJLogRecord>Out;for(const auto&R:Logs)if((F.Source.IsEmpty()||R.Source==F.Source)&&(F.TopicPrefix.IsEmpty()||R.Topic.StartsWith(F.TopicPrefix))&&(F.Contains.IsEmpty()||R.Message.Contains(F.Contains)))Out.Add(R);return Out;}
bool ATJArchiveObservability::RenderEventBus(){SetScalar(EventRailway,TEXT("EventRailway01"),1);return true;}
bool ATJArchiveObservability::RenderAuditTrail(const FString&Id){if(Id.IsEmpty())return false;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);AuditRibbons.Add(C);int32 N=0;for(const auto&R:Logs)if(R.Source==Id)++N;SetScalar(C,TEXT("AuditRibbonLength01"),FMath::Clamp(N/20.f,0.f,1.f));return true;}
bool ATJArchiveObservability::ExportLogs(ETJLogFormat,const FTJExportRange&Range){if(Range.EndSeconds<Range.StartSeconds)return false;int32 N=0;for(const auto&R:Logs)if(R.TimestampSeconds>=Range.StartSeconds&&R.TimestampSeconds<=Range.EndSeconds)++N;SetScalar(ExportCrystals,TEXT("ExportRecordCount"),(float)N);SetScalar(ExportCrystals,TEXT("ExportReady01"),N>0?1.f:0.f);return true;}
bool ATJArchiveObservability::ConfigureLogRetention(const FTJRetentionPolicy&P){if(P.MaxAgeSeconds<0)return false;Retention=P;SetScalar(RetentionShelves,TEXT("RetentionAgeSeconds"),(float)P.MaxAgeSeconds);if(P.Action==ETJRetentionAction::Clear){for(int32 i=Logs.Num()-1;i>=0;--i)if(RuntimeSeconds-Logs[i].TimestampSeconds>P.MaxAgeSeconds)Logs.RemoveAt(i);}SetScalar(RetentionShelves,TEXT("ShelfClearing01"),P.Action==ETJRetentionAction::Clear?1.f:0.f);return true;}
void ATJArchiveObservability::ApplyAudioProfile(){SetScalar(ArchiveTower,TEXT("ArchiveAudioProfile01"),bArchiveAudioProfile?1.f:0.f);}
void ATJArchiveObservability::SetListenerInsideArchive(bool B){bArchiveAudioProfile=B;ApplyAudioProfile();}
void ATJArchiveObservability::Tick(float Dt){Super::Tick(Dt);RuntimeSeconds+=Dt;for(const auto&R:Logs)if(R.TimestampSeconds+Retention.MaxAgeSeconds<RuntimeSeconds&&Retention.Action==ETJRetentionAction::Clear){SetScalar(RetentionShelves,TEXT("ShelfClearing01"),1);break;}}
ATJArchiveObservability* UTTJLogsEventsObservability::BuildArchiveTower(){if(!Archive){if(!GetWorld())return nullptr;Archive=GetWorld()->SpawnActor<ATJArchiveObservability>();Archive->BuildArchiveTower();}return Archive;}
bool UTTJLogsEventsObservability::StreamLogsToArchive(const FString&S){return Archive&&Archive->StreamLogsToArchive(S);} bool UTTJLogsEventsObservability::QueryArchive(const FTJArchiveFilter&F){return Archive&&Archive->QueryArchive(F).Num()>=0;} bool UTTJLogsEventsObservability::RenderEventBus(){return Archive&&Archive->RenderEventBus();} bool UTTJLogsEventsObservability::RenderAuditTrail(const FString&I){return Archive&&Archive->RenderAuditTrail(I);} bool UTTJLogsEventsObservability::ExportLogs(ETJLogFormat F,const FTJExportRange&R){return Archive&&Archive->ExportLogs(F,R);} bool UTTJLogsEventsObservability::ConfigureLogRetention(const FTJRetentionPolicy&P){return Archive&&Archive->ConfigureLogRetention(P);}