#include "MarketplaceDistrict.h"
#include "Engine/World.h"
#include "Materials/MaterialInstanceDynamic.h"
ATJMarketplaceDistrict::ATJMarketplaceDistrict(){ PrimaryActorTick.bCanEverTick=true; Root=CreateDefaultSubobject<USceneComponent>(TEXT("Root")); SetRootComponent(Root); Hall=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MarketplaceHall")); Hall->SetupAttachment(Root); }
void ATJMarketplaceDistrict::SetScalar(UPrimitiveComponent* C,FName P,float V) const{ if(!IsValid(C)) return; for(int32 i=0;i<C->GetNumMaterials();++i) if(auto* M=C->CreateAndSetMaterialInstanceDynamic(i)) M->SetScalarParameterValue(P,V); }
bool ATJMarketplaceDistrict::BuildHall(){ if(!IsValid(Hall)) return false; SetScalar(Hall,TEXT("MarketplaceDistrict01"),1); return true; }
void ATJMarketplaceDistrict::RegisterPackage(const FTJPackageManifest& M){if(!M.PackageId.IsEmpty()) Packages.Add(M.PackageId,M);}
bool ATJMarketplaceDistrict::RenderCatalog(const FString& Url){ if(Url.IsEmpty()) return false; CatalogPanels.Reset(); for(int32 i=0;i<Packages.Num();++i){auto* C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);C->SetRelativeLocation(FVector(i*180,0,180));CatalogPanels.Add(C);SetScalar(C,TEXT("CatalogEntry01"),1);} return true; }
void ATJMarketplaceDistrict::RenderQuarantine(const FString& Id,bool Q){auto* C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);C->SetRelativeLocation(FVector(0,500,120));QuarantineBarriers.Add(C);SetScalar(C,TEXT("QuarantineRed01"),Q?1.f:0.f);}
bool ATJMarketplaceDistrict::Inspect(const FString& Id){ if(!Packages.Contains(Id)) return false; auto& M=Packages[Id]; auto* C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);C->SetRelativeLocation(FVector(0,300,120));InspectionStands.Add(C);SetScalar(C,TEXT("Inspection01"),1); if(M.Verification!=ETJPackageVerification::Verified) RenderQuarantine(Id,true); return true; }
bool ATJMarketplaceDistrict::Verify(const FString& Id){ if(!Packages.Contains(Id)) return false; auto& M=Packages[Id]; if(M.PublicKeyBase64.IsEmpty()||M.SignatureBase64.IsEmpty()){M.Verification=ETJPackageVerification::Unverified;RenderQuarantine(Id,true);return false;} M.Verification=ETJPackageVerification::Verified; RenderQuarantine(Id,false); auto* S=NewObject<UStaticMeshComponent>(this);S->RegisterComponent();S->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);S->SetRelativeLocation(FVector(0,650,180));SignatureSeals.Add(S);SetScalar(S,TEXT("Ed25519Seal01"),1);return true; }
bool ATJMarketplaceDistrict::Install(const FString& Id,const FTJTargetPlot& Plot){if(!Packages.Contains(Id)||Plot.PlotId.IsEmpty())return false;auto& M=Packages[Id];if(M.Verification!=ETJPackageVerification::Verified){RenderQuarantine(Id,true);return false;}auto* S=NewObject<UStaticMeshComponent>(this);S->RegisterComponent();S->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);S->SetRelativeLocation(Plot.Location);InstallationStages.Add(S);SetScalar(S,TEXT("InstallationStage01"),1);return true;}
bool ATJMarketplaceDistrict::Update(const FString& Id,const FString& Version){if(!Packages.Contains(Id)||Version.IsEmpty())return false;auto& M=Packages[Id];if(M.Verification!=ETJPackageVerification::Verified)return false;M.Version=Version;auto* R=NewObject<UStaticMeshComponent>(this);R->RegisterComponent();R->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);R->SetRelativeLocation(FVector(0,-300,120));RenovationStages.Add(R);SetScalar(R,TEXT("Renovation01"),1);return true;}
bool ATJMarketplaceDistrict::Remove(const FString& Id){if(!Packages.Contains(Id))return false;auto& S=Removals.FindOrAdd(Id);S.PackageId=Id;S.Stage=ETJRemovalStage::Armed;S.LeverHoldSeconds=0;S.bDataDestroyed=false;auto* L=NewObject<UStaticMeshComponent>(this);L->RegisterComponent();L->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);L->SetRelativeLocation(FVector(0,-600,100));CustodyLevers.Add(L);SetScalar(L,TEXT("DataCustodyLever01"),1);return true;}
bool ATJMarketplaceDistrict::HoldRemovalLever(const FString& Id,float Dt){if(!Removals.Contains(Id)||Dt<=0)return false;auto& S=Removals[Id];S.LeverHoldSeconds+=Dt;if(S.LeverHoldSeconds>=3.0f){S.Stage=ETJRemovalStage::DataCustody;S.bDataDestroyed=false;}return true;}
bool ATJMarketplaceDistrict::ReleaseRemovalLever(const FString& Id){if(!Removals.Contains(Id))return false;auto& S=Removals[Id];if(S.LeverHoldSeconds<3.0f){S.Stage=ETJRemovalStage::Armed;S.bDataDestroyed=false;return false;}S.Stage=ETJRemovalStage::Destroyed;S.bDataDestroyed=true;return true;}
void ATJMarketplaceDistrict::Tick(float Dt){Super::Tick(Dt);}
bool ATJMarketplaceDistrict::AddRegistry(const FTJRegistrySource& S){if(S.RegistryId.IsEmpty()||S.RegistryUrl.IsEmpty())return false;Registries.Add(S.RegistryId,S);return true;}
bool ATJMarketplaceDistrict::RemoveRegistry(const FString& Id){return Registries.Remove(Id)>0;}

ATJMarketplaceDistrict* UTJMarketplaceDistrict::BuildMarketplaceDistrict(){if(!District){UWorld*W=GetWorld();if(!IsValid(W))return nullptr;District=W->SpawnActor<ATJMarketplaceDistrict>();}return District->BuildHall()?District:nullptr;}
bool UTJMarketplaceDistrict::RenderRegistryCatalog(const FString& Url){return District&&District->RenderCatalog(Url);}
bool UTJMarketplaceDistrict::InspectPackage(const FString& Id){return District&&District->Inspect(Id);}
bool UTJMarketplaceDistrict::InstallPackage(const FString& Id,const FTJTargetPlot& P){return District&&District->Install(Id,P);}
bool UTJMarketplaceDistrict::VerifyPackageSignature(const FString& Id){return District&&District->Verify(Id);}
bool UTJMarketplaceDistrict::UpdatePackage(const FString& Id,const FString& V){return District&&District->Update(Id,V);}
bool UTJMarketplaceDistrict::RemovePackage(const FString& Id){return District&&District->Remove(Id);}
bool UTJMarketplaceDistrict::ManageRegistrySources(){return IsValid(District);}
bool UTJMarketplaceDistrict::HoldRemovalLever(const FString& Id,float Dt){return District&&District->HoldRemovalLever(Id,Dt);}
bool UTJMarketplaceDistrict::ReleaseRemovalLever(const FString& Id){return District&&District->ReleaseRemovalLever(Id);}
void UTJMarketplaceDistrict::RegisterPackage(const FTJPackageManifest& M){if(District)District->RegisterPackage(M);}
void UTJMarketplaceDistrict::RegisterRegistry(const FTJRegistrySource& S){if(District)District->AddRegistry(S);}
