#include "IdentityAuthDevices.h"
ATJIdentityGatehouse::ATJIdentityGatehouse(){PrimaryActorTick.bCanEverTick=true;Root=CreateDefaultSubobject<USceneComponent>(TEXT("Root"));SetRootComponent(Root);Gate=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("AuthDoor"));Gate->SetupAttachment(Root);AuthBeam=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("AuthorizationBeam"));AuthBeam->SetupAttachment(Root);DeniedPlacard=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("DeniedPlacard"));DeniedPlacard->SetupAttachment(Root);Ledger=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("AccessLedger"));Ledger->SetupAttachment(Root);FleetControl=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("FleetControlRoom"));FleetControl->SetupAttachment(Root);}
void ATJIdentityGatehouse::SetScalar(UPrimitiveComponent*C,FName P,float V)const{if(!C)return;for(int32 i=0;i<C->GetNumMaterials();++i)if(auto*M=C->CreateAndSetMaterialInstanceDynamic(i))M->SetScalarParameterValue(P,V);}
void ATJIdentityGatehouse::SetDoor(ETJDoorAuthState S){const float A=S==ETJDoorAuthState::Authorized?1.f:0.f,D=S==ETJDoorAuthState::Denied?1.f:0.f;SetScalar(AuthBeam,TEXT("AuthorizationBeam01"),A);SetScalar(DeniedPlacard,TEXT("DeniedPlacard01"),D);SetScalar(Gate,TEXT("DoorOpen01"),A);}
bool ATJIdentityGatehouse::RegisterDevice(const FTJDeviceIdentity&D){if(D.DeviceId.IsEmpty()||D.ExpectedSignature.IsEmpty()||Devices.Contains(D.DeviceId))return false;Devices.Add(D.DeviceId,D);return true;}
bool ATJIdentityGatehouse::RevokeDevice(const FString&Id){auto*D=Devices.Find(Id);if(!D)return false;D->State=ETJDeviceState::Revoked;RenderDeviceAvatar(Id);return true;}
bool ATJIdentityGatehouse::RenderDeviceAvatar(const FString&Id){const auto*D=Devices.Find(Id);if(!D)return false;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);Avatars.Add(C);SetScalar(C,TEXT("DeviceRevoked01"),D->State==ETJDeviceState::Revoked?1.f:0.f);if(D->State==ETJDeviceState::Revoked){SetScalar(C,TEXT("StoneTransition01"),1.f);C->SetVisibility(false,true);}return true;}
bool ATJIdentityGatehouse::RenderKeycard(const FString&Id,const TArray<FString>&P){const auto*D=Devices.Find(Id);if(!D||D->State==ETJDeviceState::Revoked)return false;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);Keycards.Add(C);SetScalar(C,TEXT("PermissionStripeCount"),FMath::Clamp((float)P.Num(),0.f,16.f));return true;}
bool ATJIdentityGatehouse::AuthenticateDevice(const FString&Id,const FString&Sig){const auto*D=Devices.Find(Id);const bool Valid=D&&D->State==ETJDeviceState::Active&&!Sig.IsEmpty()&&Sig==D->ExpectedSignature;AccessHistory.Add({RuntimeSeconds,Id,Valid,Valid?TEXT("authorized"):(!D?TEXT("unknown-device"):(D->State==ETJDeviceState::Revoked?TEXT("revoked-device"):TEXT("invalid-signature")))});SetDoor(Valid?ETJDoorAuthState::Authorized:ETJDoorAuthState::Denied);return Valid;}
bool ATJIdentityGatehouse::RenderLocalAuthCookie(const FTJLocalAuthSession&S){if(S.SessionId.IsEmpty()||S.DeviceId.IsEmpty()||S.ExpiresAtSeconds<=S.IssuedAtSeconds)return false;auto*C=NewObject<UStaticMeshComponent>(this);C->RegisterComponent();C->AttachToComponent(Root,FAttachmentTransformRules::KeepRelativeTransform);Passes.Add(C);SetScalar(C,TEXT("AuthPassValid01"),S.bRevoked?0.f:1.f);return true;}
bool ATJIdentityGatehouse::ManageDeviceFleet(){SetScalar(FleetControl,TEXT("FleetDeviceCount"),(float)Devices.Num());SetScalar(FleetControl,TEXT("FleetRevokedCount"),(float)Algo::CountIf(Devices,[](const TPair<FString,FTJDeviceIdentity>&P){return P.Value.State==ETJDeviceState::Revoked;}));return true;}
bool ATJIdentityGatehouse::RenderAccessLog(){SetScalar(Ledger,TEXT("AccessEntryCount"),(float)AccessHistory.Num());return true;}
void ATJIdentityGatehouse::Tick(float Dt){Super::Tick(Dt);RuntimeSeconds+=Dt;}
ATJIdentityGatehouse* UTJIdentityAuthDevices::BuildGatehouse(){if(!Gatehouse){if(!GetWorld())return nullptr;Gatehouse=GetWorld()->SpawnActor<ATJIdentityGatehouse>();}return Gatehouse;}
bool UTJIdentityAuthDevices::RenderDeviceAvatar(const FString&Id){return Gatehouse&&Gatehouse->RenderDeviceAvatar(Id);} bool UTJIdentityAuthDevices::RenderKeycard(const FString&Id,const TArray<FString>&P){return Gatehouse&&Gatehouse->RenderKeycard(Id,P);} bool UTJIdentityAuthDevices::AuthenticateDevice(const FString&Id,const FString&S){return Gatehouse&&Gatehouse->AuthenticateDevice(Id,S);} bool UTJIdentityAuthDevices::RenderLocalAuthCookie(const FTJLocalAuthSession&S){return Gatehouse&&Gatehouse->RenderLocalAuthCookie(S);} bool UTJIdentityAuthDevices::ManageDeviceFleet(){return Gatehouse&&Gatehouse->ManageDeviceFleet();} bool UTJIdentityAuthDevices::RenderAccessLog(){return Gatehouse&&Gatehouse->RenderAccessLog();} bool UTJIdentityAuthDevices::RegisterDevice(const FTJDeviceIdentity&D){return Gatehouse&&Gatehouse->RegisterDevice(D);} bool UTJIdentityAuthDevices::RevokeDevice(const FString&Id){return Gatehouse&&Gatehouse->RevokeDevice(Id);}