#include "HUDPanelsInspection.h"
void UTJHUDClientStateStore::PublishHUD(const FTJHUDState&V){HUD=V;OnStateChanged.Broadcast();} void UTJHUDClientStateStore::PublishPanel(const FString&K,const FTJPanelState&V){Panels.Add(K,V);OnStateChanged.Broadcast();} void UTJHUDClientStateStore::PublishOverlay(ETJOverlayMode V){Overlay=V;OnStateChanged.Broadcast();} void UTJHUDClientStateStore::PublishDebugLayer(const FString&K,bool V){DebugLayers.Add(K,V);OnStateChanged.Broadcast();} void UTJHUDClientStateStore::PublishSearch(const FString&V){SearchQuery=V;OnStateChanged.Broadcast();}
bool UTJHUDPanelsInspection::RenderHUD(const FTJHUDState&V){if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishHUD(V);return true;}
bool UTJHUDPanelsInspection::RenderServicePanel(const FString&P){if(P.IsEmpty())return false;if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishPanel(P,{P,true,TEXT("service inspector")});return true;}
bool UTJHUDPanelsInspection::RenderContainerPanel(const FString&C){if(C.IsEmpty())return false;if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishPanel(C,{C,true,TEXT("deep container inspection")});return true;}
bool UTJHUDPanelsInspection::RenderNetworkOverlay(ETJOverlayMode M){if(M!=ETJOverlayMode::Topology)return false;if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishOverlay(M);return true;}
bool UTJHUDPanelsInspection::RenderXRayOverlay(ETJOverlayMode M){if(M!=ETJOverlayMode::XRay)return false;if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishOverlay(M);return true;}
bool UTJHUDPanelsInspection::RenderDependencyOverlay(){if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishOverlay(ETJOverlayMode::Dependencies);return true;}
bool UTJHUDPanelsInspection::RenderDebugOverlay(const FString&L){if(L.IsEmpty())return false;if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishDebugLayer(L,true);return true;}
bool UTJHUDPanelsInspection::RenderSearchAndNavigate(const FString&Q){if(Q.IsEmpty())return false;if(!StateStore)StateStore=NewObject<UTJHUDClientStateStore>(this);StateStore->PublishSearch(Q);return true;}