#include "UpdatesSigningIntegrity.h"
ATJUpdateIntegrityDistrict::ATJUpdateIntegrityDistrict(){Root=CreateDefaultSubobject<USceneComponent>(TEXT("Root"));SetRootComponent(Root);Delivery=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("UpdateDelivery"));Delivery->SetupAttachment(Root);RenovationCrew=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("RenovationCrew"));RenovationCrew->SetupAttachment(Root);SignatureSeal=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("SignatureSeal"));SignatureSeal->SetupAttachment(Root);RollbackRestoration=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("RollbackRestoration"));RollbackRestoration->SetupAttachment(Root);MerkleTree=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MerkleTree"));MerkleTree->SetupAttachment(Root);HistoryModels=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("VersionHistoryModels"));HistoryModels->SetupAttachment(Root);}
void ATJUpdateIntegrityDistrict::SetScalar(UPrimitiveComponent*C,FName P,float V)const{if(!C)return;for(int32 i=0;i<C->GetNumMaterials();++i)if(auto*M=C->CreateAndSetMaterialInstanceDynamic(i))M->SetScalarParameterValue(P,V);}
bool ATJUpdateIntegrityDistrict::RenderUpdateAvailable(const FString&P,const FString&V){if(P.IsEmpty()||V.IsEmpty())return false;auto&R=Updates.FindOrAdd(P);R={P,V,ETJUpdateState::AwaitingSignature,false};History.FindOrAdd(P).Add(R);SetScalar(Delivery,TEXT("UpdateAvailable01"),1);SetScalar(SignatureSeal,TEXT("SignatureRequired01"),1);SetScalar(RenovationCrew,TEXT("CrewRefused01"),1);return true;}
bool ATJUpdateIntegrityDistrict::VerifyUpdateSignature(const FString&P,const FString&S){auto*R=Updates.Find(P);if(!R||S.IsEmpty())return false;R->bSignatureVerified=(S==FString::Printf(TEXT("sig:%s:%s"),*P,*R->Version));R->State=R->bSignatureVerified?ETJUpdateState::Available:ETJUpdateState::Blocked;SetScalar(SignatureSeal,TEXT("SealVerified01"),R->bSignatureVerified?1.f:0.f);SetScalar(RenovationCrew,TEXT("CrewRefused01"),R->bSignatureVerified?0.f:1.f);return R->bSignatureVerified;}
bool ATJUpdateIntegrityDistrict::RenderUpdateInProgress(const FString&P){auto*R=Updates.Find(P);if(!R||!R->bSignatureVerified)return false;R->State=ETJUpdateState::InProgress;SetScalar(RenovationCrew,TEXT("RenovationActive01"),1);SetScalar(RenovationCrew,TEXT("CrewRefused01"),0);return true;}
bool ATJUpdateIntegrityDistrict::RenderRollback(const FString&P,const FString&V){auto*R=Updates.Find(P);if(!R||V.IsEmpty())return false;R->State=ETJUpdateState::RolledBack;R->Version=V;SetScalar(RollbackRestoration,TEXT("ArchitecturalRestoration01"),1);return true;}
bool ATJUpdateIntegrityDistrict::RenderPackageIntegrityCheck(const FString&P){if(P.IsEmpty())return false;SetScalar(MerkleTree,TEXT("MerkleIntegrity01"),1);return true;}
bool ATJUpdateIntegrityDistrict::RenderUpdateHistory(const FString&P){auto*H=History.Find(P);if(!H)return false;SetScalar(HistoryModels,TEXT("VersionModelCount"),(float)H->Num());return true;}
ATJUpdateIntegrityDistrict* UTJUpdatesSigningIntegrity::BuildDistrict(){if(!District){if(!GetWorld())return nullptr;District=GetWorld()->SpawnActor<ATJUpdateIntegrityDistrict>();}return District;}
bool UTJUpdatesSigningIntegrity::RenderUpdateAvailable(const FString&P,const FString&V){return District&&District->RenderUpdateAvailable(P,V);} bool UTJUpdatesSigningIntegrity::RenderUpdateInProgress(const FString&P){return District&&District->RenderUpdateInProgress(P);} bool UTJUpdatesSigningIntegrity::VerifyUpdateSignature(const FString&P,const FString&S){return District&&District->VerifyUpdateSignature(P,S);} bool UTJUpdatesSigningIntegrity::RenderRollback(const FString&P,const FString&V){return District&&District->RenderRollback(P,V);} bool UTJUpdatesSigningIntegrity::RenderPackageIntegrityCheck(const FString&P){return District&&District->RenderPackageIntegrityCheck(P);} bool UTJUpdatesSigningIntegrity::RenderUpdateHistory(const FString&P){return District&&District->RenderUpdateHistory(P);}