name: TJ SPACE Nightly Cross Arch
on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:
jobs:
  cross:
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, riscv64gc-unknown-linux-gnu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cross --git https://github.com/cross-rs/cross --locked
      - run: cross test --workspace --target "${{ matrix.target }}"
      - run: cross build --workspace --release --target "${{ matrix.target }}"